import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent {
    public animes: string[] = [
        'Something',
        'Something',
        'Something',
        'Something',
        'Something',
        'Something',
        'Something',
        'Something',
        'Something',
        'Something',
    ]

    public categories: string[] = [
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
        'Some Category',
    ]
}
